# Generated by Django 2.2.13 on 2021-02-05 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls', to='main.Client'),
        ),
    ]
